POST http://localhost:4000/login
content-type: application/json

{
    "username": "nonuser",
    "password": "nonpassword"
}

###

POST http://localhost:4000/login
content-type: application/json

{
    "username": "test1",
    "password": "password1"
}