POST http://localhost:4000/addreview
content-type: application/json

{
    "review": "This is a review",
    "rating": 5,
    "location": "london",
    "username": "test1"
}

###
POST http://localhost:4000/addreview
content-type: application/json

{
    "review": "This is another review",
    "rating": 4,
    "location": "paris",
    "username": "test1"
}

###

POST http://localhost:4000/addreview
content-type: application/json

{
    "review": "You either love it or you hate it, I'm kinda neutral.",
    "rating": 3,
    "location": "brussels",
    "username": "jake"
}

###

POST http://localhost:4000/addreview
content-type: application/json

{
    "review": "Really nice, not ideal if you have a gluten intolerance though.",
    "rating": 4,
    "location": "rome",
    "username": "johndoe"
}
