POST http://localhost:4000/signup
content-type: application/json

{
    "username": "test3",
    "password": "password3"
}

###

POST http://localhost:4000/signup
content-type: application/json

{
    "username": "test4",
    "password": "password4"
}

###

POST http://localhost:4000/signup
content-type: application/json

{
    "username": "test999",
    "password": "password999"
}